apiVersion: v2
name: islandis
description: √çslandis umbrella chart
dependencies:
    - name: api-template
      repository: file://libs/api-template
      version: 0.0.1
      alias: search-indexer-service
    - name: api-template
      repository: file://libs/api-template
      version: 0.0.1
      alias: api
type: application
version: 0.0.9
