# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    tag: latest_master

web:
  namespace: islandis
  env:
    API_URL: 'http://web-api'

api:
  namespace: islandis
  secrets:
    CONTENTFUL_ACCESS_TOKEN: '/k8s/api/CONTENTFUL_ACCESS_TOKEN'
  env:
    PORT: 3333

search-indexer-service:
  namespace: search-indexer
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/services-search-indexer
  initContainer:
    create: true
    command: ["/usr/local/bin/node"]
    args: ["/webapp/migrate.js"]
  ingress:
    enabled: true
  serviceAccount:
    create: true
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 1
    min: 1
    max: 2

api:
  namespace: islandis
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/api
  ingress:
    enabled: true
  env:
    PORT: "3333"
