version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies

  - package-ecosystem: npm
    directory: /.github/actions/
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies

  - package-ecosystem: npm
    directory: /scripts/ci/cache
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies
