global:
  env:
    AUDIT_GROUP_NAME: '/island-is/audit-log'
    AWS_REGION: 'eu-west-1'
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    PORT: '3333'
    name: 'staging'
  image:
    tag: 'latest_master'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'
judicial-system-api:
  enabled: true
  env:
    ALLOW_AUTH_BYPASS: 'true'
    AUDIT_TRAIL_GROUP_NAME: 'k8s/judicial-system/audit-log'
    AUDIT_TRAIL_REGION: 'eu-west-1'
    AUDIT_TRAIL_USE_GENERIC_LOGGER: 'false'
    AUTH_AUDIENCE: 'judicial-system.staging01.devland.is'
    BACKEND_URL: 'http://web-judicial-system-backend'
    CONTENTFUL_HOST: 'cdn.contentful.com'
    HIDDEN_FEATURES: 'POLICE_CASE_FILES'
    SAML_ENTRY_POINT: 'https://innskraning.island.is/?id=judicial-system.staging'
    SERVERSIDE_FEATURES_ON: ''
    XROAD_BASE_PATH: 'http://securityserver.staging01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.staging01.devland.is/r1/IS-TEST'
    XROAD_CLIENT_ID: 'IS-TEST/GOV/5804170510/Rettarvorslugatt-Client'
    XROAD_COURT_API_PATH: '/Domstolasyslan-Private/JusticePortal-v1'
    XROAD_COURT_MEMBER_CODE: '4707171140'
    XROAD_POLICE_API_PATH: '/Logreglan-Private/loke-api-v1'
    XROAD_POLICE_MEMBER_CODE: '5306972079'
  grantNamespaces:
    - 'nginx-ingress-external'
  grantNamespacesEnabled: true
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/judicial-system-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'judicial-system.staging01.devland.is'
          paths:
            - '/api'
  namespace: 'judicial-system'
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 3
    min: 2
  secrets:
    AUTH_JWT_SECRET: '/k8s/judicial-system/AUTH_JWT_SECRET'
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    CONTENTFUL_ACCESS_TOKEN: '/k8s/judicial-system/CONTENTFUL_ACCESS_TOKEN'
    COURTS_CREDENTIALS: '/k8s/judicial-system/COURTS_CREDENTIALS'
    SECRET_TOKEN: '/k8s/judicial-system/SECRET_TOKEN'
    XROAD_CLIENT_CERT: '/k8s/judicial-system/XROAD_CLIENT_CERT'
    XROAD_CLIENT_KEY: '/k8s/judicial-system/XROAD_CLIENT_KEY'
    XROAD_CLIENT_PEM: '/k8s/judicial-system/XROAD_CLIENT_PEM'
    XROAD_COURTS_CREDENTIALS: '/k8s/judicial-system/COURTS_CREDENTIALS'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::261174024191:role/judicial-system-api'
    create: true
    name: 'judicial-system-api'
judicial-system-backend:
  enabled: true
  env:
    CONTENTFUL_HOST: 'cdn.contentful.com'
    DB_HOST: 'postgres-applications.internal'
    DB_NAME: 'judicial_system'
    DB_USER: 'judicial_system'
    DOKOBIT_URL: 'https://developers.dokobit.com'
    EMAIL_REGION: 'eu-west-1'
    NODE_OPTIONS: '--max-old-space-size=464'
    S3_BUCKET: 'island-is-staging-upload-judicial-system'
    S3_REGION: 'eu-west-1'
    S3_TIME_TO_LIVE_GET: '5'
    S3_TIME_TO_LIVE_POST: '15'
    SERVERSIDE_FEATURES_ON: ''
    XROAD_BASE_PATH_WITH_ENV: 'https://securityserver.staging01.devland.is/r1/IS-TEST'
    XROAD_CLIENT_ID: 'IS-TEST/GOV/5804170510/Rettarvorslugatt-Client'
    XROAD_COURT_MEMBER_CODE: '4707171140'
    XROAD_POLICE_MEMBER_CODE: '5306972079'
  grantNamespaces:
    - 'nginx-ingress-external'
  grantNamespacesEnabled: true
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/judicial-system-backend'
  initContainer:
    containers:
      - args:
          - 'sequelize-cli'
          - 'db:migrate'
        command:
          - 'npx'
    env:
      DB_HOST: 'postgres-applications.internal'
      DB_NAME: 'judicial_system'
      DB_USER: 'judicial_system'
      SERVERSIDE_FEATURES_ON: ''
    secrets:
      DB_PASS: '/k8s/judicial-system/DB_PASSWORD'
  namespace: 'judicial-system'
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 4
    max: 10
    min: 4
  resources:
    limits:
      cpu: '400m'
      memory: '512Mi'
    requests:
      cpu: '100m'
      memory: '256Mi'
  secrets:
    ADMIN_USERS: '/k8s/judicial-system/ADMIN_USERS'
    AUTH_JWT_SECRET: '/k8s/judicial-system/AUTH_JWT_SECRET'
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    CONTENTFUL_ACCESS_TOKEN: '/k8s/judicial-system/CONTENTFUL_ACCESS_TOKEN'
    COURTS_CREDENTIALS: '/k8s/judicial-system/COURTS_CREDENTIALS'
    COURTS_MOBILE_NUMBERS: '/k8s/judicial-system/COURTS_MOBILE_NUMBERS'
    DB_PASS: '/k8s/judicial-system/DB_PASSWORD'
    DOKOBIT_ACCESS_TOKEN: '/k8s/judicial-system/DOKOBIT_ACCESS_TOKEN'
    EMAIL_FROM: '/k8s/judicial-system/EMAIL_FROM'
    EMAIL_FROM_NAME: '/k8s/judicial-system/EMAIL_FROM_NAME'
    EMAIL_REPLY_TO: '/k8s/judicial-system/EMAIL_REPLY_TO'
    EMAIL_REPLY_TO_NAME: '/k8s/judicial-system/EMAIL_REPLY_TO_NAME'
    EVENT_URL: '/k8s/judicial-system/EVENT_URL'
    NOVA_PASSWORD: '/k8s/judicial-system/NOVA_PASSWORD'
    NOVA_URL: '/k8s/judicial-system/NOVA_URL'
    NOVA_USERNAME: '/k8s/judicial-system/NOVA_USERNAME'
    PRISON_ADMIN_EMAIL: '/k8s/judicial-system/PRISON_ADMIN_EMAIL'
    PRISON_EMAIL: '/k8s/judicial-system/PRISON_EMAIL'
    SECRET_TOKEN: '/k8s/judicial-system/SECRET_TOKEN'
    XROAD_CLIENT_CERT: '/k8s/judicial-system/XROAD_CLIENT_CERT'
    XROAD_CLIENT_KEY: '/k8s/judicial-system/XROAD_CLIENT_KEY'
    XROAD_CLIENT_PEM: '/k8s/judicial-system/XROAD_CLIENT_PEM'
    XROAD_COURT_API_PATH: '/k8s/judicial-system/XROAD_COURT_API_PATH'
    XROAD_POLICE_API_PATH: '/k8s/judicial-system/XROAD_POLICE_API_PATH'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::261174024191:role/judicial-system-backend'
    create: true
    name: 'judicial-system-backend'
judicial-system-web:
  enabled: true
  env:
    API_URL: 'https://judicial-system.staging01.devland.is'
    INTERNAL_API_URL: 'http://web-judicial-system-api'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces:
    - 'nginx-ingress-external'
  grantNamespacesEnabled: true
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/readiness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/judicial-system-web'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'judicial-system.staging01.devland.is'
          paths:
            - '/'
  namespace: 'judicial-system'
  replicaCount:
    default: 2
    max: 3
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
judicial-system-xrd-api:
  enabled: true
  env:
    AUDIT_TRAIL_GROUP_NAME: 'k8s/judicial-system/audit-log'
    AUDIT_TRAIL_REGION: 'eu-west-1'
    AUDIT_TRAIL_USE_GENERIC_LOGGER: 'false'
    BACKEND_URL: 'http://web-judicial-system-backend'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces:
    - 'nginx-ingress-internal'
  grantNamespacesEnabled: true
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/judicial-system-xrd-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'judicial-system-xrd-api.internal.staging01.devland.is'
          paths:
            - '/'
  namespace: 'judicial-system'
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 3
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    SECRET_TOKEN: '/k8s/judicial-system/SECRET_TOKEN'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::261174024191:role/judicial-system-xrd-api'
    create: true
    name: 'judicial-system-xrd-api'
