version: '3.3'

services:
  db_gjafakort_application:
    ports:
      - 5432:5432

  redis_cluster:
    container_name: redis_cluster
    image: grokzen/redis-cluster:5.0.6
    privileged: true
    sysctls:
      net.core.somaxconn: '511'
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'

  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.1
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=sns:4575,sqs:4576
    ports:
      - "4575:4575"
      - "4576:4576"
