apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gjafakort-api.fullname" . }}
  labels:
    {{- include "gjafakort-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.default }}
  selector:
    matchLabels:
      {{- include "gjafakort-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gjafakort-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gjafakort-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            {{- with .Values.environment }}
            - name: RSK_URL
              value: {{ .rsk_url }}
            - name: RSK_USERNAME
              value: {{ .rsk_username }}
            - name: RSK_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gjafakort-api
                  key: RSK_API_PASSWORD
            - name: FERDALAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gjafakort-api
                  key: FERDALAG_API_KEY
            - name: FERDALAG_URL
              value: {{ .ferdalag_url }}
            - name: APPLICATION_URL
              value: {{ .application_url }}
            - name: SAML_ENTRY_POINT
              value: {{ .saml_entry_point }}
            - name: AUTH_AUDIENCE
              value: {{ .auth_audience }}
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gjafakort-api
                  key: AUTH_JWT_SECRET
            - name: REDIS_URL
              value: {{ .redis_url }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
