version: '3.3'

services:
  db:
    image: postgres:11.6
    container_name: db
    networks:
      - local
    environment:
      - POSTGRES_PASSWORD=XjFsvIrGyCCrdE
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DEV_DB_USER=dev_db
      - DEV_DB_PASS=dev_db
      - DEV_DB_NAME=dev_db
    volumes:
      - ./bin/startup.sql:/docker-entrypoint-initdb.d/startup.sql


networks:
  local:
