apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels: {{- include "web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP
      name: http
  selector: {{- include "web.selectorLabels" . | nindent 4 }}
