version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/ci/Dockerfile.test
      args:
        DB_NAME: db_skilavottord_backend
        APP: skilavottord-backend
    networks:
      - local
    depends_on:
      - db_skilavottord_backend
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db_skilavottord_backend
    volumes:
      - ../..:/code

  db_skilavottord_backend:
    ports: []
