openapi: 3.0.0
info:
  title: Judicial System Backend
  description: This is the backend api for the judicial system.
  version: '1.0'
  contact: {}
tags:
  - name: judicial-system
    description: ''
servers: []
components:
  schemas:
    Liveness:
      type: object
      properties:
        ok:
          type: boolean
      required:
        - ok
    Version:
      type: object
      properties:
        version:
          type: string
      required:
        - version
    Case:
      type: object
      properties:
        created:
          format: date-time
          type: string
        modified:
          format: date-time
          type: string
        description:
          type: string
        policeCaseNumber:
          type: string
        suspectNationalId:
          type: string
        suspectName:
          type: string
        state:
          type: string
          enum:
            - UNKNOWN
            - DRAFT
            - SUBMITTED
            - ACTIVE
            - COMPLETED
      required:
        - created
        - modified
        - description
        - policeCaseNumber
        - suspectNationalId
        - suspectName
        - state
    CreateCaseDto:
      type: object
      properties:
        description:
          type: string
        policeCaseNumber:
          type: string
        suspectNationalId:
          type: string
        suspectName:
          type: string
      required:
        - description
        - policeCaseNumber
        - suspectNationalId
        - suspectName
    UpdateCaseDto:
      type: object
      properties:
        description:
          type: string
        policeCaseNumber:
          type: string
        suspectNationalId:
          type: string
        suspectName:
          type: string
        state:
          type: string
          enum:
            - UNKNOWN
            - DRAFT
            - SUBMITTED
            - ACTIVE
            - COMPLETED
      required:
        - policeCaseNumber
        - suspectNationalId
        - suspectName
paths:
  /liveness:
    get:
      operationId: InfraController_liveness
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Liveness'
      tags:
        - internal
  /version:
    get:
      operationId: InfraController_version
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      tags:
        - internal
  /api/cases:
    get:
      operationId: CaseController_getAll
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
      tags:
        - case
  '/api/case/{id}':
    get:
      operationId: CaseController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - case
    put:
      operationId: CaseController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCaseDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - case
  /api/case:
    post:
      operationId: CaseController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCaseDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - case
