openapi: 3.0.0
info:
  title: Judicial System Backend
  description: This is the backend api for the judicial system.
  version: '1.0'
  contact: {}
tags:
  - name: judicial-system
    description: ''
servers: []
components:
  schemas:
    Liveness:
      type: object
      properties:
        ok:
          type: boolean
      required:
        - ok
    Version:
      type: object
      properties:
        version:
          type: string
      required:
        - version
    User:
      type: object
      properties:
        nationalId:
          type: string
        roles:
          type: array
          items:
            type: string
      required:
        - nationalId
        - roles
    Case:
      type: object
      properties:
        created:
          format: date-time
          type: string
        modified:
          format: date-time
          type: string
        state:
          type: string
          enum:
            - UNKNOWN
            - DRAFT
            - SUBMITTED
            - ACTIVE
            - COMPLETED
        policeCaseNumber:
          type: string
        suspectNationalId:
          type: string
        suspectName:
          type: string
        suspectAddress:
          type: string
        court:
          type: string
        arrestDate:
          format: date-time
          type: string
        requestedCourtDate:
          format: date-time
          type: string
        requestedCustodyEndDate:
          format: date-time
          type: string
        lawsBroken:
          type: string
        custodyProvisions:
          type: string
          enum:
            - _95_1_A
            - _95_1_B
            - _95_1_C
            - _95_1_D
            - _95_2
            - _99_1_B
        custodyRestrictions:
          type: string
          enum:
            - ISOLATION
            - VISITAION
            - COMMUNICATION
            - MEDIA
        caseFacts:
          type: string
        witnessAccounts:
          type: string
        investigationProgress:
          type: string
        legalArguments:
          type: string
        comments:
          type: string
      required:
        - created
        - modified
        - state
        - policeCaseNumber
        - suspectNationalId
        - custodyProvisions
        - custodyRestrictions
    CreateCaseDto:
      type: object
      properties:
        policeCaseNumber:
          type: string
        suspectNationalId:
          type: string
        suspectName:
          type: string
        suspectAddress:
          type: string
        court:
          type: string
        arrestDate:
          format: date-time
          type: string
        requestedCourtDate:
          format: date-time
          type: string
        requestedCustodyEndDate:
          format: date-time
          type: string
      required:
        - policeCaseNumber
        - suspectNationalId
    UpdateCaseDto:
      type: object
      properties:
        state:
          type: string
          enum:
            - UNKNOWN
            - DRAFT
            - SUBMITTED
            - ACTIVE
            - COMPLETED
        policeCaseNumber:
          type: string
        suspectNationalId:
          type: string
        suspectName:
          type: string
        suspectAddress:
          type: string
        court:
          type: string
        arrestDate:
          format: date-time
          type: string
        requestedCourtDate:
          format: date-time
          type: string
        requestedCustodyEndDate:
          format: date-time
          type: string
        lawsBroken:
          type: string
        custodyProvisions:
          type: string
          enum:
            - ISOLATION
            - VISITAION
            - COMMUNICATION
            - MEDIA
        custodyRestrictions:
          type: string
          enum:
            - ISOLATION
            - VISITAION
            - COMMUNICATION
            - MEDIA
        caseFacts:
          type: string
        witnessAccounts:
          type: string
        investigationProgress:
          type: string
        legalArguments:
          type: string
        comments:
          type: string
paths:
  /liveness:
    get:
      operationId: InfraController_liveness
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Liveness'
      tags:
        - internal
  /version:
    get:
      operationId: InfraController_version
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      tags:
        - internal
  /api/auth/callback:
    post:
      operationId: AuthController_callback
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - authentication
  /api/auth/login:
    get:
      operationId: AuthController_login
      parameters:
        - name: returnUrl
          required: true
          in: query
          schema:
            type: ''
      responses:
        '200':
          description: ''
      tags:
        - authentication
  /api/auth/logout:
    get:
      operationId: AuthController_logout
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - authentication
  /api/user:
    get:
      operationId: UserController_getCurrentUser
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - users
  /api/cases:
    get:
      operationId: CaseController_getAll
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
      tags:
        - cases
  '/api/case/{id}':
    get:
      operationId: CaseController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
    put:
      operationId: CaseController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCaseDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
  /api/case:
    post:
      operationId: CaseController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCaseDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
