openapi: 3.0.0
info:
  title: Judicial System Backend
  description: This is the backend api for the judicial system.
  version: '1.0'
  contact: {}
tags:
  - name: judicial-system
    description: ''
servers: []
components:
  schemas:
    Liveness:
      type: object
      properties:
        ok:
          type: boolean
      required:
        - ok
    Version:
      type: object
      properties:
        version:
          type: string
      required:
        - version
    User:
      type: object
      properties:
        id:
          type: string
        created:
          format: date-time
          type: string
        modified:
          format: date-time
          type: string
        nationalId:
          type: string
        name:
          type: string
        mobileNumber:
          type: string
        role:
          type: string
          enum:
            - PROSECUTOR
            - REGISTRAR
            - JUDGE
      required:
        - id
        - created
        - modified
        - nationalId
        - name
        - mobileNumber
        - role
    CreateCaseDto:
      type: object
      properties:
        policeCaseNumber:
          type: string
        accusedNationalId:
          type: string
        accusedName:
          type: string
        accusedAddress:
          type: string
        court:
          type: string
        arrestDate:
          format: date-time
          type: string
        requestedCourtDate:
          format: date-time
          type: string
      required:
        - policeCaseNumber
        - accusedNationalId
    Notification:
      type: object
      properties:
        id:
          type: string
        created:
          format: date-time
          type: string
        caseId:
          type: string
        type:
          type: string
          enum:
            - HEADS_UP
            - READY_FOR_COURT
        message:
          type: string
      required:
        - id
        - created
        - caseId
        - type
        - message
    Case:
      type: object
      properties:
        id:
          type: string
        created:
          format: date-time
          type: string
        modified:
          format: date-time
          type: string
        state:
          type: string
          enum:
            - DRAFT
            - SUBMITTED
            - ACCEPTED
            - REJECTED
        policeCaseNumber:
          type: string
        accusedNationalId:
          type: string
        accusedName:
          type: string
        accusedAddress:
          type: string
        court:
          type: string
        arrestDate:
          format: date-time
          type: string
        requestedCourtDate:
          format: date-time
          type: string
        requestedCustodyEndDate:
          format: date-time
          type: string
        lawsBroken:
          type: string
        custodyProvisions:
          type: array
          items:
            type: string
            enum:
              - _95_1_A
              - _95_1_B
              - _95_1_C
              - _95_1_D
              - _95_2
              - _99_1_B
        requestedCustodyRestrictions:
          type: array
          items:
            type: string
            enum:
              - ISOLATION
              - VISITAION
              - COMMUNICATION
              - MEDIA
        caseFacts:
          type: string
        witnessAccounts:
          type: string
        investigationProgress:
          type: string
        legalArguments:
          type: string
        comments:
          type: string
        courtCaseNumber:
          type: string
        courtStartTime:
          format: date-time
          type: string
        courtEndTime:
          format: date-time
          type: string
        courtAttendees:
          type: string
        policeDemands:
          type: string
        accusedPlea:
          type: string
        litigationPresentations:
          type: string
        ruling:
          type: string
        custodyEndDate:
          format: date-time
          type: string
        custodyRestrictions:
          type: array
          items:
            type: string
            enum:
              - ISOLATION
              - VISITAION
              - COMMUNICATION
              - MEDIA
        accusedAppealDecision:
          type: string
          enum:
            - APPEAL
            - ACCEPT
            - POSTPONE
        prosecutorAppealDecision:
          type: string
          enum:
            - APPEAL
            - ACCEPT
            - POSTPONE
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
      required:
        - id
        - created
        - modified
        - state
        - policeCaseNumber
        - accusedNationalId
        - accusedName
        - accusedAddress
        - court
        - arrestDate
        - requestedCourtDate
        - requestedCustodyEndDate
        - lawsBroken
        - custodyProvisions
        - requestedCustodyRestrictions
        - caseFacts
        - witnessAccounts
        - investigationProgress
        - legalArguments
        - comments
        - courtCaseNumber
        - courtStartTime
        - courtEndTime
        - courtAttendees
        - policeDemands
        - accusedPlea
        - litigationPresentations
        - ruling
        - custodyEndDate
        - custodyRestrictions
        - accusedAppealDecision
        - prosecutorAppealDecision
        - notifications
    UpdateCaseDto:
      type: object
      properties:
        state:
          type: string
          enum:
            - DRAFT
            - SUBMITTED
            - ACCEPTED
            - REJECTED
        policeCaseNumber:
          type: string
        accusedNationalId:
          type: string
        accusedName:
          type: string
        accusedAddress:
          type: string
        court:
          type: string
        arrestDate:
          format: date-time
          type: string
        requestedCourtDate:
          format: date-time
          type: string
        requestedCustodyEndDate:
          format: date-time
          type: string
        lawsBroken:
          type: string
        custodyProvisions:
          type: array
          items:
            type: string
            enum:
              - _95_1_A
              - _95_1_B
              - _95_1_C
              - _95_1_D
              - _95_2
              - _99_1_B
        requestedCustodyRestrictions:
          type: array
          items:
            type: string
            enum:
              - ISOLATION
              - VISITAION
              - COMMUNICATION
              - MEDIA
        caseFacts:
          type: string
        witnessAccounts:
          type: string
        investigationProgress:
          type: string
        legalArguments:
          type: string
        comments:
          type: string
        courtCaseNumber:
          type: string
        courtStartTime:
          format: date-time
          type: string
        courtEndTime:
          format: date-time
          type: string
        courtAttendees:
          type: string
        policeDemands:
          type: string
        accusedPlea:
          type: string
        litigationPresentations:
          type: string
        ruling:
          type: string
        custodyEndDate:
          format: date-time
          type: string
        custodyRestrictions:
          type: array
          items:
            type: string
            enum:
              - ISOLATION
              - VISITAION
              - COMMUNICATION
              - MEDIA
        accusedAppealDecision:
          type: string
          enum:
            - APPEAL
            - ACCEPT
            - POSTPONE
        prosecutorAppealDecision:
          type: string
          enum:
            - APPEAL
            - ACCEPT
            - POSTPONE
    TransitionCaseDto:
      type: object
      properties:
        modified:
          format: date-time
          type: string
        transition:
          type: string
          enum:
            - SUBMIT
            - ACCEPT
            - REJECT
      required:
        - modified
        - transition
    SigningServiceResponse:
      type: object
      properties:
        controlCode:
          type: string
        documentToken:
          type: string
      required:
        - controlCode
        - documentToken
paths:
  /liveness:
    get:
      operationId: InfraController_liveness
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Liveness'
      tags:
        - internal
  /version:
    get:
      operationId: InfraController_version
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      tags:
        - internal
  /api/auth/callback:
    post:
      operationId: AuthController_callback
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - authentication
  /api/auth/login:
    get:
      operationId: AuthController_login
      parameters:
        - name: returnUrl
          required: true
          in: query
          schema:
            type: ''
      responses:
        '200':
          description: ''
      tags:
        - authentication
  /api/auth/logout:
    get:
      operationId: AuthController_logout
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - authentication
  /api/user:
    get:
      operationId: UserController_getCurrentUser
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - users
  '/api/user/{nationalId}/admin':
    get:
      operationId: UserController_updateUserRole
      parameters:
        - name: nationalId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - users
  /api/case:
    post:
      operationId: CaseController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCaseDto'
      responses:
        '201':
          description: Creates a new case
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
  '/api/case/{id}':
    put:
      operationId: CaseController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCaseDto'
      responses:
        '200':
          description: Updates an existing case
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
    get:
      operationId: CaseController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Gets an existing case
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
  '/api/case/{id}/state':
    put:
      operationId: CaseController_transition
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransitionCaseDto'
      responses:
        '200':
          description: Transitions an existing case to a new state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
  /api/cases:
    get:
      operationId: CaseController_getAll
      parameters: []
      responses:
        '200':
          description: Gets all existing cases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
      tags:
        - cases
  '/api/case/{id}/notification':
    post:
      operationId: CaseController_sendNotificationByCaseId
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '201':
          description: Sends a new notification for an existing case
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
      tags:
        - cases
  '/api/case/{id}/notifications':
    get:
      operationId: CaseController_getAllNotificationsById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Gets all existing notifications for an existing case
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
      tags:
        - cases
  '/api/case/{id}/signature':
    post:
      operationId: CaseController_requestSignature
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '201':
          description: Requests a signature for an existing case
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SigningServiceResponse'
      tags:
        - cases
    get:
      operationId: CaseController_confirmSignature
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
        - name: documentToken
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Confirms a previously requested signature for an existing case
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
      tags:
        - cases
