apiVersion: v2
name: islandis
description: √çslandis umbrella chart
dependencies:
  - name: namespaces
    repository: file://libs/namespaces
    version: 0.0.1
    alias: namespaces
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: search-indexer-service
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: web
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: service-portal-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: skilavottord-ws
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: service-portal
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: skilavottord-web
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: island-ui-storybook
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: api-catalogue
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: xroad-collector
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: application-system-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: application-system-form
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: services-documents
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: contentful-translation-extension
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: download-service
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: icelandic-names-registry-backend
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: endorsement-system-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: temporary-voter-registry-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: party-letter-registry-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: endorsement-system-scripts-update-metadata
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: air-discount-scheme-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: air-discount-scheme-backend
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: air-discount-scheme-web
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: github-actions-cache
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: user-notification
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: user-notification-worker
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: external-contracts-tests
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: application-system-api-worker
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: regulations-admin-backend
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: contentful-entry-tagger-service
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: mock-server
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: portals-admin
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: consultation-portal
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: license-api
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: services-sessions
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: services-sessions-worker
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: services-sessions-geoip-worker
  - name: api-template
    repository: file://libs/api-template
    version: 0.0.1
    alias: contentful-apps
type: application
version: 0.0.9
