version: '3.3'

services:
  db_application_system:
    image: public.ecr.aws/bitnami/postgresql:11.12.0
    container_name: db_application_system
    networks:
      - local
    environment:
      - POSTGRES_PASSWORD=XjFsvIrGyCCrdE
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DEV_DB_USER=dev_db
      - DEV_DB_PASS=dev_db
      - DEV_DB_NAME=dev_db
    volumes:
      - ./bin/startup.sql:/docker-entrypoint-initdb.d/startup.sql

  redis_cluster:
    container_name: redis_cluster
    image: grokzen/redis-cluster:5.0.6
    privileged: true
    sysctls:
      net.core.somaxconn: '511'
    environment:
      - IP=0.0.0.0

networks:
  local:
