air-discount-scheme-api:
  enabled: true
  env:
    AUTH_AUDIENCE: 'loftbru.island.is'
    BACKEND_URL: 'http://web-air-discount-scheme-backend'
    CONTENTFUL_HOST: 'cdn.contentful.com'
    ELASTIC_NODE: 'https://vpc-search-mw4w5c2m2g5edjrtvwbpzhkw24.eu-west-1.es.amazonaws.com'
    SAML_ENTRY_POINT: 'https://innskraning.island.is/?id=ads.prod'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: 'loftbru.island.is'
          paths:
            - '/api'
  namespace: 'air-discount-scheme'
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 10
    min: 2
  secrets:
    ADMINS: '/k8s/air-discount-scheme/api/ADMINS'
    AUTH_JWT_SECRET: '/k8s/air-discount-scheme/api/AUTH_JWT_SECRET'
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    CONTENTFUL_ACCESS_TOKEN: '/k8s/air-discount-scheme/api/CONTENTFUL_ACCESS_TOKEN'
    DEVELOPERS: '/k8s/air-discount-scheme/api/DEVELOPERS'
    SENTRY_DSN: '/k8s/air-discount-scheme-api/SENTRY_DSN'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::251502586493:role/air-discount-scheme-api'
    create: true
    name: 'air-discount-scheme-api'
air-discount-scheme-backend:
  enabled: true
  env:
    DB_HOST: 'postgres-applications.internal'
    DB_NAME: 'air_discount_scheme_backend'
    DB_USER: 'air_discount_scheme_backend'
    ENVIRONMENT: 'prod'
    NATIONAL_REGISTRY_URL: 'https://skeyti.advania.is/ords/slrv/registry/v1.0'
    REDIS_URL_NODE_01: 'clustercfg.general-redis-cluster-group.whakos.euw1.cache.amazonaws.com:6379'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-backend'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: 'loftbru.island.is'
          paths:
            - '/api/swagger'
            - '/api/public'
  initContainer:
    containers:
      - args:
          - 'sequelize-cli'
          - 'db:migrate'
        command:
          - 'npx'
    env:
      DB_HOST: 'postgres-applications.internal'
      DB_NAME: 'air_discount_scheme_backend'
      DB_USER: 'air_discount_scheme_backend'
      SERVERSIDE_FEATURES_ON: ''
    secrets:
      DB_PASS: '/k8s/air-discount-scheme/backend/DB_PASSWORD'
  namespace: 'air-discount-scheme'
  replicaCount:
    default: 2
    max: 10
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    DB_PASS: '/k8s/air-discount-scheme/backend/DB_PASSWORD'
    ERNIR_API_KEY: '/k8s/air-discount-scheme/backend/ERNIR_API_KEY'
    ICELANDAIR_API_KEY: '/k8s/air-discount-scheme/backend/ICELANDAIR_API_KEY'
    NATIONAL_REGISTRY_PASSWORD: '/k8s/air-discount-scheme/backend/NATIONAL_REGISTRY_PASSWORD'
    NATIONAL_REGISTRY_USERNAME: '/k8s/air-discount-scheme/backend/NATIONAL_REGISTRY_USERNAME'
    NORLANDAIR_API_KEY: '/k8s/air-discount-scheme/backend/NORLANDAIR_API_KEY'
    SENTRY_DSN: '/k8s/air-discount-scheme-backend/SENTRY_DSN'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
air-discount-scheme-web:
  enabled: true
  env:
    API_URL: 'http://web-air-discount-scheme-api'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/readiness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-web'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/configuration-snippet: 'rewrite /$ https://island.is/loftbru; rewrite /en$ https://island.is/en/lower-airfares-for-residents-in-rural-areas;'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: 'loftbru.island.is'
          paths:
            - '/'
  namespace: 'air-discount-scheme'
  replicaCount:
    default: 2
    max: 10
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    SENTRY_DSN: '/k8s/air-discount-scheme-api/SENTRY_DSN'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
global:
  env:
    AUDIT_GROUP_NAME: '/island-is/audit-log'
    AWS_REGION: 'eu-west-1'
    IDENTITY_SERVER_ISSUER_URL: 'https://innskra.island.is'
    PORT: '3333'
    name: 'prod'
  image:
    tag: 'latest_master'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'
