apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-foo-1741245501698
spec:
  template:
    spec:
      containers:
        - command:
            - sh
            - '-c'
            - >-
              echo "This is a noop container to make sure we always have at
              least one container!"
          env: []
          image: 'public.ecr.aws/runecast/busybox:1.35.0'
          name: noop
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      restartPolicy: Never
      serviceAccountName: feature-deployment

