# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  env:
    name: 'dev'
    AWS_REGION: 'eu-west-1'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'

air-discount-scheme-api:
  env:

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'devland-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.dev01.devland.is'
        paths:
          - '/api'
    tls:
      - hosts: ['ads.dev01.devland.is']
        secretName: 'air-discount-scheme-web-tls'

air-discount-scheme-web:
  env:

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'devland-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.dev01.devland.is'
        paths:
          - '/'
    tls:
      - hosts: ['ads.dev01.devland.is']
        secretName: 'air-discount-scheme-web-tls'

air-discount-scheme-backend:
  env:
    DB_HOST: 'dev-vidspyrna-aurora-1.c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
    DB_NAME: 'air_discount_scheme_backend'
    DB_USER: 'air_discount_scheme_backend'

  initContainer:
    env:
      DB_HOST: 'dev-vidspyrna-aurora-1.c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
      DB_NAME: 'air_discount_scheme_backend'
      DB_USER: 'air_discount_scheme_backend'

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'devland-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.dev01.devland.is'
        paths:
          - '/api/swagger'
          - '/api/public'
    tls:
      - hosts: ['ads.dev01.devland.is']
        secretName: 'air-discount-scheme-web-tls'
