appId: 'is.island.app.dev'
---
- runFlow: utils/launch-and-sign-in.yaml
- runFlow:
    file: 'utils/select-tab.yaml'
    env:
      title: 'Umsóknir'

- assertVisible:
    id: 'APPLICATION_ITEM'
- runFlow:
    when:
      visible:
        text: '.*Sjá allt.*'
    commands:
      - tapOn:
          text: 'Ókláraðar umsóknir Sjá allt'
      - assertVisible:
          id: 'SCREEN_APPLICATIONS_DETAILS'
      - assertVisible:
          id: 'APPLICATION_ITEM'
      - tapOn:
          text: 'Opna umsókn'
      # Need to make sure preferences are reset for this to pass, if the user has already hasOnboardedPasskeys: true then this will fail
      - assertVisible:
          id: 'SCREEN_PASSKEY'
      - tapOn:
          id: 'NAVBAR_SHEET_CLOSE_BUTTON'
- tapOn:
    text: 'Umsóknir'
