auth-admin-web:
  enabled: true
  env:
    BASE_URL: 'https://identity-server.dev01.devland.is/admin'
    IDENTITYSERVER_DOMAIN: 'identity-server.dev01.devland.is'
    NEXTAUTH_URL: 'https://identity-server.dev01.devland.is/admin/api/auth'
    NEXT_PUBLIC_BACKEND_URL: '/backend'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 10
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-web'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
        nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      hosts:
        - host: 'identity-server.dev01.devland.is'
          paths:
            - '/admin'
  namespace: 'identity-server-admin'
  replicaCount:
    default: 2
    max: 10
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '200m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  service:
    targetPort: 4200
global:
  env:
    AUDIT_GROUP_NAME: '/identity-server/audit-log'
    AWS_REGION: 'eu-west-1'
    PORT: '3333'
    name: 'dev'
  image:
    tag: 'latest_master'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'
identity-server:
  enabled: true
  env:
    ASPNETCORE_URLS: 'http://*:5000'
    AWS__CloudWatch__AuditLogGroup: '/identity-server/audit-log'
    AWS__SystemsManager__ParameterStore__DataProtectionPrefix: '/k8s/identity-server/DataProtectionSecret'
    Application__MinCompletionPortThreads: '10'
    AudkenniSettings__Retries: '24'
    AudkenniSettings__Url: 'https://tqd75.audkenni.is:443/sso/'
    CORECLR_ENABLE_PROFILING: '1'
    CORECLR_PROFILER: '{846F5F1C-F9AE-4B07-969E-05C26BC060D8}'
    CORECLR_PROFILER_PATH: '/opt/datadog/Datadog.Trace.ClrProfiler.Native.so'
    CacheSettings__Enabled: 'true'
    CacheSettings__Memcached__Address: 'identity-server.5fzau3.cfg.euw1.cache.amazonaws.com'
    CacheSettings__Memcached__Port: '11211'
    CacheSettings__Redis__Address: 'clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com'
    CacheSettings__Redis__Port: '6379'
    DD_DOTNET_TRACER_HOME: '/opt/datadog'
    DD_INTEGRATIONS: '/opt/datadog/integrations.json'
    Datadog__Metrics__Port: '5003'
    IdentityServer__EnableFakeLogin: 'true'
    IdentityServer__EnableFeatureDeploymentWildcards: 'true'
    IdentityServer__SigningCertificate__Path: '/etc/config/ids-signing.pfx'
    NODE_OPTIONS: '--max-old-space-size=208'
    PersistenceSettings__BaseAddress: 'http://web-services-auth-api'
    PersistenceSettings__UserProfileBaseAddress: 'http://web-service-portal-api.service-portal.svc.cluster.local'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
  files:
    - 'ids-signing.pfx'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    port: 5010
    readiness:
      initialDelaySeconds: 3
      path: '/readiness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/identity-server'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
        nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      hosts:
        - host: 'identity-server.dev01.devland.is'
          paths:
            - '/'
  namespace: 'identity-server'
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    AudkenniSettings__ClientId: '/k8s/identity-server-audkenni/AudkenniClientId'
    AudkenniSettings__ClientSecret: '/k8s/identity-server-audkenni/AudkenniClientSecret'
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    FeatureFlags__ConfigCatSdkKey: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    IdentityServer__FakePersons: '/k8s/identity-server/FakePersons'
    IdentityServer__SigningCertificate__Passphrase: '/k8s/identity-server/SigningCertificatePassphrase'
    PersistenceSettings__AccessTokenManagementSettings__ClientSecret: '/k8s/identity-server/ClientSecret'
    Scopes__Admin__RootAccessList: '/k8s/identity-server/AdminRootAccessList'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  service:
    targetPort: 5000
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::013313053092:role/identity-server'
    create: true
    name: 'identity-server'
namespaces:
  labels: {}
  namespaces:
    - 'identity-server'
    - 'identity-server-admin'
    - 'personal-representative'
services-auth-admin-api:
  enabled: true
  env:
    DB_HOST: 'postgres-applications.internal'
    DB_NAME: 'servicesauth'
    DB_REPLICAS_HOST: 'dev-vidspyrna-aurora.cluster-ro-c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
    DB_USER: 'servicesauth'
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.dev01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 10
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/services-auth-admin-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.dev01.devland.is'
          paths:
            - '/backend'
  namespace: 'identity-server-admin'
  replicaCount:
    default: 2
    max: 10
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    DB_PASS: '/k8s/services-auth/api/DB_PASSWORD'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
services-auth-api:
  enabled: true
  env:
    COMPANY_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379"]'
    COMPANY_REGISTRY_XROAD_PROVIDER_ID: 'IS-DEV/GOV/10006/Skatturinn/ft-v1'
    DB_HOST: 'postgres-applications.internal'
    DB_NAME: 'servicesauth'
    DB_REPLICAS_HOST: 'dev-vidspyrna-aurora.cluster-ro-c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
    DB_USER: 'servicesauth'
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.dev01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://identity-server.dev01.devland.is/api'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
    USER_PROFILE_CLIENT_URL: 'http://web-service-portal-api.service-portal.svc.cluster.local'
    XROAD_BASE_PATH: 'http://securityserver.dev01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.dev01.devland.is/r1/IS-DEV'
    XROAD_CLIENT_ID: 'IS-DEV/GOV/10000/island-is-client'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS-DEV/GOV/10001/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_PROCURING_PATH: 'IS-DEV/GOV/10006/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379"]'
    XROAD_TJODSKRA_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_TJODSKRA_MEMBER_CODE: '10001'
    XROAD_TLS_BASE_PATH: 'https://securityserver.dev01.devland.is'
    XROAD_TLS_BASE_PATH_WITH_ENV: 'https://securityserver.dev01.devland.is/r1/IS-DEV'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 10
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/services-auth-api'
  initContainer:
    containers:
      - args:
          - 'sequelize-cli'
          - 'db:migrate'
        command:
          - 'npx'
        name: 'migrations'
        resources:
          limits:
            cpu: '200m'
            memory: '256Mi'
          requests:
            cpu: '100m'
            memory: '128Mi'
      - args:
          - 'sequelize-cli'
          - 'db:seed:all'
        command:
          - 'npx'
        name: 'seed'
        resources:
          limits:
            cpu: '200m'
            memory: '256Mi'
          requests:
            cpu: '100m'
            memory: '128Mi'
    env:
      DB_HOST: 'postgres-applications.internal'
      DB_NAME: 'servicesauth'
      DB_REPLICAS_HOST: 'dev-vidspyrna-aurora.cluster-ro-c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
      DB_USER: 'servicesauth'
      SERVERSIDE_FEATURES_ON: 'INAO_Client'
    secrets:
      DB_PASS: '/k8s/services-auth/api/DB_PASSWORD'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 10
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    DB_PASS: '/k8s/services-auth/api/DB_PASSWORD'
    RSK_PASSWORD: '/k8s/xroad/client/RSK/PASSWORD'
    RSK_USERNAME: '/k8s/xroad/client/RSK/USERNAME'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
services-auth-public-api:
  enabled: true
  env:
    DB_HOST: 'postgres-applications.internal'
    DB_NAME: 'servicesauth'
    DB_REPLICAS_HOST: 'dev-vidspyrna-aurora.cluster-ro-c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
    DB_USER: 'servicesauth'
    IDENTITY_SERVER_CLIENT_ID: '@island.is/clients/auth-api'
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.dev01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://identity-server.dev01.devland.is/api'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
    XROAD_BASE_PATH: 'http://securityserver.dev01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.dev01.devland.is/r1/IS-DEV'
    XROAD_CLIENT_ID: 'IS-DEV/GOV/10000/island-is-client'
    XROAD_NATIONAL_REGISTRY_ACTOR_TOKEN: 'true'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS-DEV/GOV/10001/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_PROCURING_PATH: 'IS-DEV/GOV/10006/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379"]'
    XROAD_TJODSKRA_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_TJODSKRA_MEMBER_CODE: '10001'
    XROAD_TLS_BASE_PATH: 'https://securityserver.dev01.devland.is'
    XROAD_TLS_BASE_PATH_WITH_ENV: 'https://securityserver.dev01.devland.is/r1/IS-DEV'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 10
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/services-auth-public-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
        nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      hosts:
        - host: 'identity-server.dev01.devland.is'
          paths:
            - '/api(/|$)(.*)'
  namespace: 'identity-server-admin'
  replicaCount:
    default: 2
    max: 10
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    DB_PASS: '/k8s/services-auth/api/DB_PASSWORD'
    IDENTITY_SERVER_CLIENT_SECRET: '/k8s/services-auth/IDENTITY_SERVER_CLIENT_SECRET'
    NATIONAL_REGISTRY_IDS_CLIENT_SECRET: '/k8s/xroad/client/NATIONAL-REGISTRY/IDENTITYSERVER_SECRET'
    RSK_PASSWORD: '/k8s/xroad/client/RSK/PASSWORD'
    RSK_USERNAME: '/k8s/xroad/client/RSK/USERNAME'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
services-personal-representative:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.dev01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 10
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/services-personal-representative'
  ingress:
    demo-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'personal-representative-xrd.dev01.devland.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.dev01.devland.is'
          paths:
            - '/'
  namespace: 'personal-representative'
  replicaCount:
    default: 2
    max: 10
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
services-personal-representative-public:
  enabled: true
  env:
    DB_REPLICAS_HOST: 'dev-vidspyrna-aurora.cluster-ro-c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.dev01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'INAO_Client'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 10
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/services-personal-representative-public'
  ingress:
    demo-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'personal-representative-public-xrd.dev01.devland.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-public-xrd.internal.dev01.devland.is'
          paths:
            - '/'
  namespace: 'personal-representative'
  replicaCount:
    default: 2
    max: 10
    min: 2
  resources:
    limits:
      cpu: '400m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
